"""Render the Marketplace screenshots in images/ from the built theme files.

Run after build_themes.py:  python scripts/build_screenshots.py
Needs Microsoft Edge (or set the EDGE environment variable to a Chrome/Edge path).
"""
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEASONS = ("Autumn", "Winter", "Spring", "Summer")
EDGE = os.environ.get("EDGE", r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe")

# CSS variable used by preview/shot.html -> where its color comes from in the theme file
UI = {
    "bg": "editor.background", "text": "editor.foreground", "chrome": "sideBar.background",
    "line": "sideBar.border", "muted": "tab.inactiveForeground", "accent": "tab.activeBorderTop",
    "status": "statusBar.foreground", "selList": "list.activeSelectionBackground",
    "raise": "editor.lineHighlightBackground", "sel": "editor.selectionBackground",
    "lnum": "editorLineNumber.foreground", "info": "gitDecoration.modifiedResourceForeground",
    "ok": "gitDecoration.addedResourceForeground",
}
SYNTAX = {
    "keyword": "keyword", "function": "entity.name.function", "string": "string", "type": "entity.name.type",
    "number": "constant.numeric", "constant": "constant.language", "comment": "comment",
}


def season_vars(theme):
    scope_colors = {}
    for rule in theme["tokenColors"]:
        scopes = rule["scope"] if isinstance(rule["scope"], list) else [rule["scope"]]
        for scope in scopes:
            scope_colors.setdefault(scope, rule["settings"].get("foreground"))
    return {**{var: theme["colors"][key] for var, key in UI.items()},
            **{var: scope_colors[scope] for var, scope in SYNTAX.items()}}


def main():
    palettes = {s: season_vars(json.loads((ROOT / "themes" / f"quarterlight-{s.lower()}.json")
                                          .read_text(encoding="utf-8"))) for s in SEASONS}
    (ROOT / "preview" / "vars.js").write_text(
        "// Generated by scripts/build_screenshots.py\n"
        f"const PALETTES = {json.dumps(palettes, indent=2)};\n"
        "const palette = PALETTES[SEASON] || PALETTES.Autumn;\n"
        "for (const [name, color] of Object.entries(palette)) {\n"
        "  document.documentElement.style.setProperty(`--${name}`, color);\n"
        "}\n"
        "document.getElementById(\"name\").textContent = `Quarterlight ${SEASON}`;\n",
        encoding="utf-8")

    page = (ROOT / "preview" / "shot.html").as_uri()
    (ROOT / "images").mkdir(exist_ok=True)
    for season in SEASONS:
        subprocess.run([EDGE, "--headless=new", "--disable-gpu", "--hide-scrollbars",
                        "--allow-file-access-from-files", "--force-device-scale-factor=1",
                        "--window-size=1280,760", "--virtual-time-budget=3000",
                        f"--screenshot={ROOT / 'images' / (season.lower() + '.png')}",
                        f"{page}#{season}"], check=True, capture_output=True)
        print(f"images/{season.lower()}.png")


if __name__ == "__main__":
    main()
